pr: [master]

trigger: [master]

pool:
  vmImage: 'Ubuntu 16.04'

steps:
  - task: NodeTool@0
    inputs:
      versionSpec: '10.x'
    displayName: 'Install Node.js'

  - script: |
      yarn
    displayName: yarn

  - script: |
      yarn build
    displayName: yarn build

  - script: |
      yarn test
    displayName: yarn test

  - script: |
      yarn lint
    displayName: yarn lint

  - script: |
      yarn checkchange
    displayName: yarn check for change files

  - script: |
      yarn workspace @fluentui/scripts just projrefs:verify
    displayName: yarn check for correct tsconfig.json project references
